//
// Created by Christopher Szatmary on 2018-12-10.
//

#ifndef DATA_STRUCTURES_AND_ALGORITHMS_ARRAY_STACK_TEST_H
#define DATA_STRUCTURES_AND_ALGORITHMS_ARRAY_STACK_TEST_H

void run_array_stack_tests();

#endif //DATA_STRUCTURES_AND_ALGORITHMS_ARRAY_STACK_TEST_H
