//
// Created by Christopher Szatmary on 2018-12-09.
//

#ifndef DATA_STRUCTURES_AND_ALGORITHMS_LIST_STACK_TEST_H
#define DATA_STRUCTURES_AND_ALGORITHMS_LIST_STACK_TEST_H

void run_list_stack_tests();

#endif //DATA_STRUCTURES_AND_ALGORITHMS_LIST_STACK_TEST_H
